# Usage:
# Set these private variables in gitlab-ci environment:
#   CI_JOB_TOKEN
#   DOCKER_LOGIN

variables:
  REGISTRY: nexus.instantlinux.net
  GIT_SSL_NO_VERIFY: "1"

stages:
  - ui
  - Functional Tests
  - Promote Images
  - Clean

before_script:
  - export TAG=bld_$CI_PIPELINE_IID_${CI_COMMIT_SHA:0:7}

.registry_template: &registry_login
  before_script:
  - export TAG=bld_$CI_PIPELINE_IID_${CI_COMMIT_SHA:0:7}
  - docker login -u $DOCKER_LOGIN -p $CI_JOB_TOKEN $REGISTRY

.create_image_template: &create_image
  script: make create_image && echo k8s/$CI_JOB_STAGE >> .targets

create_apicrud_ui:
  stage: ui
  <<: *registry_login
  <<: *create_image

test:
  stage: Functional Tests
  script: make test_functional

promote_images:
  stage: Promote Images
  <<: *registry_login
  script: IMAGES=`cat .targets` make promote_images
  only: { refs: [ master ] }

clean:
  stage: Clean
  script: make clean_images
  when: always
